import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export const workspaceSourcePaths = {
	chordIndex: fileURLToPath(new URL("./packages/chord/src/index.ts", import.meta.url)),
	chordContext: fileURLToPath(new URL("./packages/chord/src/context/index.ts", import.meta.url)),
	chordDelta: fileURLToPath(new URL("./packages/chord/src/delta/index.ts", import.meta.url)),
	chordBundler: fileURLToPath(new URL("./packages/chord/src/bundler.ts", import.meta.url)),
	chordNode: fileURLToPath(new URL("./packages/chord/src/node.ts", import.meta.url)),
	telemetryIndex: fileURLToPath(new URL("./packages/telemetry/src/index.ts", import.meta.url)),
	telemetryTesting: fileURLToPath(new URL("./packages/telemetry/src/testing/index.ts", import.meta.url)),
	mcpIndex: fileURLToPath(new URL("./packages/mcp/src/index.ts", import.meta.url)),
	mcpOAuth: fileURLToPath(new URL("./packages/mcp/src/oauth/index.ts", import.meta.url)),
	mcpTesting: fileURLToPath(new URL("./packages/mcp/src/testing/index.ts", import.meta.url)),
	aiIndex: fileURLToPath(new URL("./packages/ai/src/index.ts", import.meta.url)),
	aiCompat: fileURLToPath(new URL("./packages/ai/src/compat.ts", import.meta.url)),
	aiOAuth: fileURLToPath(new URL("./packages/ai/src/oauth.ts", import.meta.url)),
	aiApi: fileURLToPath(new URL("./packages/ai/src/api", import.meta.url)),
	aiProviders: fileURLToPath(new URL("./packages/ai/src/providers", import.meta.url)),
	aiUtils: fileURLToPath(new URL("./packages/ai/src/utils", import.meta.url)),
	agentIndex: fileURLToPath(new URL("./packages/agent/src/index.ts", import.meta.url)),
	codemodeIndex: fileURLToPath(new URL("./packages/codemode/src/index.ts", import.meta.url)),
	codemodeDeclarations: fileURLToPath(new URL("./packages/codemode/src/declarations.ts", import.meta.url)),
	codemodeSource: fileURLToPath(new URL("./packages/codemode/src/source.ts", import.meta.url)),
	protocolIndex: fileURLToPath(new URL("./packages/protocol/src/index.ts", import.meta.url)),
	clientIndex: fileURLToPath(new URL("./packages/client/src/index.ts", import.meta.url)),
	clientUnix: fileURLToPath(new URL("./packages/client/src/unix.ts", import.meta.url)),
	serverIndex: fileURLToPath(new URL("./packages/server/src/index.ts", import.meta.url)),
	serverUnix: fileURLToPath(new URL("./packages/server/src/transports/unix/index.ts", import.meta.url)),
	codingAgentIndex: fileURLToPath(new URL("./packages/coding-agent/src/index.ts", import.meta.url)),
	tuiIndex: fileURLToPath(new URL("./packages/tui/src/index.ts", import.meta.url)),
} as const;

export default defineConfig({
	resolve: {
		alias: [
			{ find: /^@jeffhub\/jeff-code-chord$/, replacement: workspaceSourcePaths.chordIndex },
			{ find: /^@jeffhub\/jeff-code-chord\/context$/, replacement: workspaceSourcePaths.chordContext },
			{ find: /^@jeffhub\/jeff-code-chord\/delta$/, replacement: workspaceSourcePaths.chordDelta },
			{ find: /^@jeffhub\/jeff-code-chord\/bundler$/, replacement: workspaceSourcePaths.chordBundler },
			{ find: /^@jeffhub\/jeff-code-chord\/node$/, replacement: workspaceSourcePaths.chordNode },
			{ find: /^@jeffhub\/jeff-code-telemetry$/, replacement: workspaceSourcePaths.telemetryIndex },
			{ find: /^@jeffhub\/jeff-code-telemetry\/testing$/, replacement: workspaceSourcePaths.telemetryTesting },
			{ find: /^@jeffhub\/jeff-code-mcp$/, replacement: workspaceSourcePaths.mcpIndex },
			{ find: /^@jeffhub\/jeff-code-mcp\/oauth$/, replacement: workspaceSourcePaths.mcpOAuth },
			{ find: /^@jeffhub\/jeff-code-mcp\/testing$/, replacement: workspaceSourcePaths.mcpTesting },
			{ find: /^@jeffhub\/jeff-code-ai$/, replacement: workspaceSourcePaths.aiIndex },
			{ find: /^@jeffhub\/jeff-code-ai\/compat$/, replacement: workspaceSourcePaths.aiCompat },
			{ find: /^@jeffhub\/jeff-code-ai\/oauth$/, replacement: workspaceSourcePaths.aiOAuth },
			{
				find: /^@jeffhub\/jeff-code-ai\/utils\/(.+)$/,
				replacement: `${workspaceSourcePaths.aiUtils}/$1.ts`,
			},
			{
				find: /^@jeffhub\/jeff-code-ai\/api\/(.+)$/,
				replacement: `${workspaceSourcePaths.aiApi}/$1.ts`,
			},
			{
				find: /^@jeffhub\/jeff-code-ai\/providers\/(.+)$/,
				replacement: `${workspaceSourcePaths.aiProviders}/$1.ts`,
			},
			{ find: /^@jeffhub\/jeff-code-agent-core$/, replacement: workspaceSourcePaths.agentIndex },
			{ find: /^@jeffhub\/jeff-code-codemode$/, replacement: workspaceSourcePaths.codemodeIndex },
			{ find: /^@jeffhub\/jeff-code-codemode\/declarations$/, replacement: workspaceSourcePaths.codemodeDeclarations },
			{ find: /^@jeffhub\/jeff-code-codemode\/source$/, replacement: workspaceSourcePaths.codemodeSource },
			{ find: /^@jeffhub\/jeff-code-protocol$/, replacement: workspaceSourcePaths.protocolIndex },
			{ find: /^@jeffhub\/jeff-code-client$/, replacement: workspaceSourcePaths.clientIndex },
			{ find: /^@jeffhub\/jeff-code-client\/unix$/, replacement: workspaceSourcePaths.clientUnix },
			{ find: /^@jeffhub\/jeff-code-server$/, replacement: workspaceSourcePaths.serverIndex },
			{ find: /^@jeffhub\/jeff-code-server\/unix$/, replacement: workspaceSourcePaths.serverUnix },
			{ find: /^@jeffhub\/jeff-code-tui$/, replacement: workspaceSourcePaths.tuiIndex },
		],
	},
});
